### ISSUE TITLE
Thanks for your great job! Is it the c++ version of Guide-Missile-Simulation? 

### ISSUE THREAD

**Issue by theorynice** [bgin/Guided-Missile-Modeling-Simulation#3]
Thanks for your work very much! Is this the repository independent on the https://github.com/bgin/Guided_Missile_Simulation? Whether can I run the GMS_perf_test_ComputeGrassParamEq_zmm16r4_call_scope_non_looped_non_instr.cpp without downloading the repo of https://github.com/bgin/Guided_Missile_Simulation ? Which platform can it run in? Windows?Ubuntu?or Both? Thank you!

**Comment by bgin** [comment]
Hello

Thank you very much for your kind words!!

`Is this the repository independent on the https://github.com/bgin/Guided_Missile_Simulation? `

Yes this (C++) repository is independent from Fortran repository, so you can build it and run it independently from Fortran version.
Speaking more accurately the C++ version is a port of Fortran version, but C++ version will rely heavily on Fortran implementation.

> Whether can I run the GMS_perf_test_ComputeGrassParamEq_zmm16r4_call_scope_non_looped_non_instr.cpp without downloading the repo of https://github.com/bgin/Guided_Missile_Simulation ? 

You will need an appropriate source files which reside in relevant repository, secondly this test requires a hardware support of AVX512 ISA  compatible CPU.

> Which platform can it run in? Windows?Ubuntu?or Both? 

If you mean test itself -- then  it will run both on Windows and Linux (OS agnostic code).
Generally the support of Windows was removed from the repository (both C++ and Fortran) versions.
I have done that in order to enable a precise manual instrumentation of the run-time performance.

Bear in mind, that both repositories will not have any fancy GUI are not a game or game engine and will not execute in real-time.
Those will be a console applications dumping some output to file.

The main idea is to simulate and model the signal radar processing, which in turn is based on van Tress books and other authors books.
The project is in early alpha stage , although constant progress is made.
I pay a lot attention to optimize as much as possible the code.

Best regards

Bernard

**Comment by theorynice** [comment]
@bgin 
Thanks for your kind reply. It's helpful for me very much. I am trying to run the test file but failed to build this. If does it need the specified compiler(intel or vs compiler) or IDE. When I compile the test.cpp by DEV C++， the issue comes up with failing to find the _mkl.h_.  I cant find this mkl.h in both repository. How can I link the MKL developed by intel to this project?

> You will need an appropriate source files which reside in relevant repository
Can I know the appropriate source files by debuging the test file(by reminding me of losing the relevent file)

**Comment by bgin** [comment]
> When I compile the test.cpp by DEV C++， the issue comes up with failing to find the mkl.h. I cant find this mkl.h in both repository

For the test file **"GMS_perf_test_ComputeGrassParamEq_zmm16r4_call_scope_non_looped_non_instr.cpp"**  you do not need a MKL library, but you will need to program MSR registers before running that test (you may also remove the PMC measurement code) which lives in GMS_fast_pmc_access.h.
You can compile that test file with either ICC or GCC. You can not run this executable on Windows because there are a Linux specific syscalls unless you will undefine MMAP macro.

> Can I know the appropriate source files by debuging the test file(by reminding me of losing the relevent file)

Put it simply -- clone the whole repository, i.e.  [ https://github.com/bgin/Guided-Missile-Modeling-Simulation](url)

**Comment by bgin** [comment]
@theorynice 

Can I close the issue?

**Comment by theorynice** [comment]
Thanks for your help and great job! Best wish to you!

**Comment by bgin** [comment]
@theorynice 

Thank you very much.

Bernard
